name: CustomEffects
version: 1.0.0
main: com.customeffects.CustomEffects
api-version: '1.21'
author: 09X18 - AmplanNetwork
softdepend: ["PlaceholderAPI"]

commands:
  effectos:
    description: Abre el menú principal de efectos o gestiona vouchers.
    usage: "§c¡Uso correcto! › §7/effectos [reload | givevoucher <jugador> <id_efecto>]"
    permission: effectos.menu
    aliases: [efectos, effects]
  formato:
    description: Abre el menú de formatos de texto (bold, underline, italic).
    usage: "§c¡Uso correcto! › §7/formato"
    permission: effectos.style
    aliases: [style, formatos]
  rankeditor:
    description: Abre el editor visual de rangos en el navegador.
    usage: "§c¡Uso correcto! › §7/rankeditor"
    permission: effectos.rankeditor
    aliases: [reditor, rangoeditor]
  amigo:
    description: Sistema de amigos.
    usage: "§c¡Uso correcto! › §7/amigo [agregar | eliminar | aceptar | rechazar | lista | menu]"
    permission: effectos.friend
    aliases: [friend, amigos]

permissions:
  effectos.menu:
    description: Permite abrir el menú de efectos a los usuarios.
    default: true
  effectos.reload:
    description: Permite recargar la configuración del plugin.
    default: op
  effectos.admin:
    description: Permite generar y dar vouchers de efectos a los jugadores.
    default: op
  effectos.chat.bypass:
    description: Permite bypass el formato de chat personalizado del plugin.
    default: op
  effectos.style:
    description: Permite abrir el menú de formatos de texto.
    default: true
  effectos.rankeditor:
    description: Permite abrir el editor visual de rangos.
    default: op
  effectos.friend:
    description: Permite usar el sistema de amigos.
    default: true
  effectos.category.*:
    description: Permite ver todas las categorías del menú de efectos.
    default: true
  effectos.formato:
    description: Permite usar el comando de formato.
    default: true